/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package info.bpace.munchlife;

public final class R {
    public static final class array {
        public static final int gamemode=0x7f050001;
        public static final int gamemodeDisplay=0x7f050000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int darkgray=0x7f060001;
        public static final int tan=0x7f060000;
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int five=0x7f020001;
        public static final int four=0x7f020002;
        public static final int icon=0x7f020003;
        public static final int menu_dice=0x7f020004;
        public static final int one=0x7f020005;
        public static final int six=0x7f020006;
        public static final int three=0x7f020007;
        public static final int two=0x7f020008;
    }
    public static final class id {
        public static final int current_gear_level=0x7f090004;
        public static final int current_level=0x7f090003;
        public static final int diceroller=0x7f090009;
        public static final int down_button=0x7f090005;
        public static final int down_gear_button=0x7f090006;
        public static final int level_table=0x7f090000;
        public static final int reset=0x7f090008;
        public static final int settings=0x7f09000a;
        public static final int total_level=0x7f090007;
        public static final int up_button=0x7f090001;
        public static final int up_gear_button=0x7f090002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class menu {
        public static final int options_menu=0x7f080000;
    }
    public static final class string {
        public static final int app_name=0x7f070000;
        public static final int diceroller=0x7f070006;
        public static final int down_gear_level=0x7f070004;
        public static final int down_level=0x7f070002;
        public static final int maxlevel=0x7f07000f;
        public static final int maxlevelError=0x7f070011;
        public static final int maxlevelSummary=0x7f070010;
        public static final int ok=0x7f070009;
        /**  preferences strings 
         */
        public static final int prefTitle=0x7f07000a;
        public static final int reset=0x7f070005;
        public static final int settings=0x7f070007;
        public static final int sleep=0x7f07000b;
        public static final int sleepSummary=0x7f07000c;
        public static final int up_gear_level=0x7f070003;
        public static final int up_level=0x7f070001;
        public static final int victory=0x7f07000d;
        public static final int victorySummary=0x7f07000e;
        public static final int win=0x7f070008;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
