wget https://apt.izzysoft.de/fdroid/repo/info.puzz.a10000sentences_0.2.15.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jeroensmeets.mastodon_1.3.28.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jecelyin.editor_2.16.9.7.apk
wget https://apt.izzysoft.de/fdroid/repo/itkach.aard2_0.37.apk
wget https://apt.izzysoft.de/fdroid/repo/com.appisode.appbackuprestore_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/moe.haruue.wadb_2.4.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.seven.adclear_8.0.0.506324.apk
wget https://apt.izzysoft.de/fdroid/repo/com.adguard.android_2.9.70.apk
wget https://apt.izzysoft.de/fdroid/repo/browser.afh_1.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/kiwi.root.an2linuxclient_0.6.0.apk
wget https://apt.izzysoft.de/fdroid/repo/li.klass.fhem_4.7.5.apk
wget https://apt.izzysoft.de/fdroid/repo/org.shadowice.flocke.andotp_0.2.8.apk
wget https://apt.izzysoft.de/fdroid/repo/dev.dworks.apps.anexplorer_3.6.apk
wget https://apt.izzysoft.de/fdroid/repo/cf.vojtechh.apkmirror_3.3.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.apkupdater_1.5.9.apk
wget https://apt.izzysoft.de/fdroid/repo/com.nagopy.android.aplin_3.3.0.apk
wget https://apt.izzysoft.de/fdroid/repo/io.github.mthli.mount_1.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.anod.appwatcher_1.9.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.iiordanov.freeaRDP_v3.8.8.apk
wget https://apt.izzysoft.de/fdroid/repo/de.igloffstein.maik.aRevelation_1.0b1.apk
wget https://apt.izzysoft.de/fdroid/repo/net.somethingdreadful.MAL_2.4.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.frostchein.atlant_0.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.axet.audiorecorder_1.2.5.apk
wget https://apt.izzysoft.de/fdroid/repo/net.tjado.passwdsafe_0.2.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.lukekorth.auto_fi_0.3.0.apk
wget https://apt.izzysoft.de/fdroid/repo/taipei.sean.telegram.botplayground_1.7.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.hollandhaptics.babyapp_2016-12-09.apk
wget https://apt.izzysoft.de/fdroid/repo/com.pavelsikun.runinbackgroundpermissionsetter_1.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.ionicframework.backingtrainer763961_1.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.erakk.lnreader_1.1.49.apk
wget https://apt.izzysoft.de/fdroid/repo/com.saha.batchuninstaller_0.9.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.vlath.beheexplorer_2.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.vlath.keyboard_2017-07-30.apk
wget https://apt.izzysoft.de/fdroid/repo/com.torahsummary.betamidrash_2.01.apk
wget https://apt.izzysoft.de/fdroid/repo/se.leap.bitmaskclient.beta_0.9.7RC2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.bitpay.wallet_3.7.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.x8bit.bitwarden_1.9.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.blabbertabber.blabbertabber_0.8.3.apk
wget https://apt.izzysoft.de/fdroid/repo/cobalt.blackberrymanager_2017-10-27.apk
wget https://apt.izzysoft.de/fdroid/repo/com.savageorgiev.blockthis_112.apk
wget https://apt.izzysoft.de/fdroid/repo/org.blokada.origin.alarm_2.2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.andreapivetta.blu_53.apk
wget https://apt.izzysoft.de/fdroid/repo/org.bookdash.android_1.1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.smartjinyu.mybookshelf_1.31.apk
wget https://apt.izzysoft.de/fdroid/repo/ca.josephroque.bowlingcompanion_2.1.8.apk
wget https://apt.izzysoft.de/fdroid/repo/com.tr.expenses_1.16.apk
wget https://apt.izzysoft.de/fdroid/repo/com.bukanir.android_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/de.m4lik.burningseries_1.0.4.apk
wget https://apt.izzysoft.de/fdroid/repo/busradar.madison_1.0.38.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jrummy.busybox.installer_6.7.9.01.apk
wget https://apt.izzysoft.de/fdroid/repo/com.iiordanov.freebVNC_3.9.0.apk
wget https://apt.izzysoft.de/fdroid/repo/cgeo.geocaching_20171022.apk
wget https://apt.izzysoft.de/fdroid/repo/es.usc.citius.servando.calendula_2.4.apk
wget https://apt.izzysoft.de/fdroid/repo/de.ub0r.android.callmeter_33.11.13.apk
wget https://apt.izzysoft.de/fdroid/repo/us.koller.cameraroll_1.0.3.apk
wget https://apt.izzysoft.de/fdroid/repo/cn.nekocode.camerafilter_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/abhijith.carboncontacts_1.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.astoev.cave.survey_1.32.apk
wget https://apt.izzysoft.de/fdroid/repo/com.huetoyou.chatexchange_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/arun.com.chromer_1.7.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/cipher.root.com.cipher_2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/ca.zgrs.clipper_1.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.nightonke.cocoin_2016-04-07.apk
wget https://apt.izzysoft.de/fdroid/repo/com.coinomi.wallet_1.6.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.bubelov.coins_1.8.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.commcare.dalvik_2.40.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.pimp.companionforband_2.9.3.apk
wget https://apt.izzysoft.de/fdroid/repo/clock.socoolby.com.clock_2017-04-20.apk
wget https://apt.izzysoft.de/fdroid/repo/Cryptonite-BETA-0.7.17.apk
wget https://apt.izzysoft.de/fdroid/repo/de.pinyto.ctSESAM_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.itxtech.daedalus_1.9.0.apk
wget https://apt.izzysoft.de/fdroid/repo/hashengineering.darkcoin.wallet_5.17.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.venomvendor.sms.deduplicate_2.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.manoj.dlt_2.3.6.apk
wget https://apt.izzysoft.de/fdroid/repo/in.workarounds.define_1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/xyz.mustafaali.devqstiles_1.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/uk.co.ianfield.devstat_2.4.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.colorcloud.wifichat_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/net.mm2d.dmsexplorer_0.7.9.apk
wget https://apt.izzysoft.de/fdroid/repo/de.langerhans.wallet_3.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/net.reichholf.dreamdroid_2017-09-03.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jkenneth.droidovpn_1.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/github.daneren2005.dsub_5.3.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.vasilkoff.easyvpnfree_1.5-45.apk
wget https://apt.izzysoft.de/fdroid/repo/com.cyanogenmod.eleven_3.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.netease.qa.emmagee_2.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/org.emoncms.myapps_2.0.9.apk
wget https://apt.izzysoft.de/fdroid/repo/com.halcyonwaves.apps.energize_2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/xyz.iridiumion.enlightened_31.apk
wget https://apt.izzysoft.de/fdroid/repo/io.evercam.androidapp_2017-05-16.apk
wget https://apt.izzysoft.de/fdroid/repo/expense_manager_1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.calintat.explorer_1.0.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.openfarmanager.android_0.9.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.fastaccess.github_4.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/org.geometerplus.zlibrary.ui.android_2017-09-28.apk
wget https://apt.izzysoft.de/fdroid/repo/org.mozilla.focus_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.mozilla.klar_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.getlantern.firetweet_0.0.7.apk
wget https://apt.izzysoft.de/fdroid/repo/com.triangleleft.flashcards_1.3.apk
wget https://apt.izzysoft.de/fdroid/repo/uk.co.alt236.floatinginfo_2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/net.atomarea.flowx_2.12.apk
wget https://apt.izzysoft.de/fdroid/repo/troop.com.freedcam_3.3.147.apk
wget https://apt.izzysoft.de/fdroid/repo/org.freemp.droid_1.1.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.sylwke3100.freetrackgps_0.9.apk
wget https://apt.izzysoft.de/fdroid/repo/de.appwerft.freifunker_2016-07-14.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.funkyg.funkytunes_0.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.elixsr.portforwarder_1.4.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.xdty.gallery_1.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/GEM_0.2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.arcao.geocaching4locus_2.1.5.4.apk
wget https://apt.izzysoft.de/fdroid/repo/net.exclaimindustries.geohashdroid_0.9.2.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.daskiworks.ghwatch_1.22.apk
wget https://apt.izzysoft.de/fdroid/repo/com.example.gitnb_2017-03-26.apk
wget https://apt.izzysoft.de/fdroid/repo/com.knight.arch_1.0.6.apk
wget https://apt.izzysoft.de/fdroid/repo/com.frodo.github.android_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/giuliolodi.gitnav_1.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.gitpoint_1.3.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.alorma.github_v.4.6.1.apk
wget https://apt.izzysoft.de/fdroid/repo/org.gnucash.android_2.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.apps.adrcotfas.goodtime_1.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/dev.ldev.gpsicon_1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/eu.basicairdata.graziano.gpslogger_2017-09-30.apk
wget https://apt.izzysoft.de/fdroid/repo/com.android.gpstest_2.1.11.apk
wget https://apt.izzysoft.de/fdroid/repo/com.mendhak.gpslogger_90.apk
wget https://apt.izzysoft.de/fdroid/repo/com.benlinskey.greekreference_1.10.0.apk
wget https://apt.izzysoft.de/fdroid/repo/me.anon.grow_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.habitrpg.android.habitica_1.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/net.rfc1149.harassme_1.25.apk
wget https://apt.izzysoft.de/fdroid/repo/codes.simen.l50notifications_1.12.1.apk
wget https://apt.izzysoft.de/fdroid/repo/HeadsUp-v3.1-release.apk
wget https://apt.izzysoft.de/fdroid/repo/fr.vinetos.hellomusic_1.2.3.260115.apk
wget https://apt.izzysoft.de/fdroid/repo/com.studio4plus.homerplayer_0.7.2.apk
wget https://apt.izzysoft.de/fdroid/repo/ch.rmy.android.http_shortcuts_1.9.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.derek_s.hubble_gallery_1.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.afollestad.impression_0.8.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.mmmoussa.iqra_2.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/net.codersgarage.iseeu_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/ua.naiksoftware.j2meloader_1.2.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/JadeHS_0.5.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.njackson_3.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.marverenic.music_2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/th.in.whs.k2ausbkbd_1.3.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.shadowsocks.plugin.kcptun_0.0.6.apk
wget https://apt.izzysoft.de/fdroid/repo/org.koreader.launcher_1.4.apk
wget https://apt.izzysoft.de/fdroid/repo/co.krypt.kryptonite_2.2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.kos.ktodo_2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/ch.deletescape.lawnchair_1.1.0.1427.apk
wget https://apt.izzysoft.de/fdroid/repo/org.houxg.leamonax_1.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.linkbubble.playstore_1.9.58.apk
wget https://apt.izzysoft.de/fdroid/repo/ru.meefik.linuxdeploy_2.0.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.ianhanniballake.localstorage_2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.michaelfotiadis.locationmanagerviewer_1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.tananaev.logcat_1.7.apk
wget https://apt.izzysoft.de/fdroid/repo/com.rehanced.lunary_1.34.apk
wget https://apt.izzysoft.de/fdroid/repo/com.lostincontext_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.topjohnwu.magisk_5.4.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.tomclaw.mandarin_1.7.apk
wget https://apt.izzysoft.de/fdroid/repo/com.lyndir.masterpassword_2.4.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.bijoysingh.quicknote_2.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.pluscubed.matlog_1.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.mattermost.mattermost_3.9.apk
wget https://apt.izzysoft.de/fdroid/repo/com.geniusgithub.mediaplayer_3.5.apk
wget https://apt.izzysoft.de/fdroid/repo/github.yaa110.memento_1.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.alexstyl.specialdates_11.2.apk
wget https://apt.izzysoft.de/fdroid/repo/mensaUpb_3.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/de.thorstenwitt.mensaapp_1.6.1.apk
wget https://apt.izzysoft.de/fdroid/repo/james.metronome_1.6.apk
wget https://apt.izzysoft.de/fdroid/repo/cat.mvmike.minimalcalendarwidget_0.3.1.apk
wget https://apt.izzysoft.de/fdroid/repo/luongvo.com.todolistminimal_1.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.dominionos.music_2.4.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.m2049r.xmrwallet_1.2.4.apk
wget https://apt.izzysoft.de/fdroid/repo/open.currency_2.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.money.manager.ex_2017.11.07.apk
wget https://apt.izzysoft.de/fdroid/repo/com.yeungeek.monkeyandroid_1.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/net.yslibrary.monotweety_1.5.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.mooshim.mooshimeter_2016-09-12.apk
wget https://apt.izzysoft.de/fdroid/repo/org.ovirt.mobile.movirt_2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/is.xyz.mpv_2017-09-20-alpha.apk
wget https://apt.izzysoft.de/fdroid/repo/com.wkovacs64.mtorch_2.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.chteuchteu.munin_4.0.8.apk
wget https://apt.izzysoft.de/fdroid/repo/com.sdsmdg.harjot.MusicDNA_1.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.andreadec.musicplayer_2.5.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.rks.musicx_1.3.6.apk
wget https://apt.izzysoft.de/fdroid/repo/de.mygrades_1.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.mythtv.android_3.0.6.apk
wget https://apt.izzysoft.de/fdroid/repo/com.duy.calculator.free_3.8.5.apk
wget https://apt.izzysoft.de/fdroid/repo/io.neoterm_1.2.10.apk
wget https://apt.izzysoft.de/fdroid/repo/eu.faircode.netguard_2.99.apk
wget https://apt.izzysoft.de/fdroid/repo/com.by_syk.netupdown_1.1.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.moosd.netghost_1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/androidnetspoof-2.4.0-1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.stealthcotper.networktools_0.3.08.apk
wget https://apt.izzysoft.de/fdroid/repo/jlelse.readit_6.0.9.apk
wget https://apt.izzysoft.de/fdroid/repo/com.stardust.scriptdroid_3.0.014.apk
wget https://apt.izzysoft.de/fdroid/repo/myapplication.flashcards_2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.standardnotes_2.0.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.ocs.android.agent_2.3.0RC.apk
wget https://apt.izzysoft.de/fdroid/repo/com.sketchpunk.ocomicreader_0.2.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.kennyc.open.imgur_4.6.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.thirtydegreesray.openhub_1.7.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.nv95.openmanga_4.2.apk
wget https://apt.izzysoft.de/fdroid/repo/org.redcross.openmapkit_1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/org.openmrs.mobile_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.openorienteering.mapper_0.7.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.cnx.android_6.5.apk
wget https://apt.izzysoft.de/fdroid/repo/edu.usf.cutr.opentripplanner.android_2.1.5.apk
wget https://apt.izzysoft.de/fdroid/repo/pro.rudloff.openvegemap_0.4.3.apk
wget https://apt.izzysoft.de/fdroid/repo/universe.constellation.orion.viewer_0.74.2.apk
wget https://apt.izzysoft.de/fdroid/repo/owntracks-0.6.09.apk
wget https://apt.izzysoft.de/fdroid/repo/com.kn.paper_foss_theme_1.1.4.apk
wget https://apt.izzysoft.de/fdroid/repo/Paperwork-Android.apk
wget https://apt.izzysoft.de/fdroid/repo/com.duy.pascal.compiler_4.2.4.apk
wget https://apt.izzysoft.de/fdroid/repo/Passwy_0.2.apk
wget https://apt.izzysoft.de/fdroid/repo/pasta.streamer_1.8.apk
wget https://apt.izzysoft.de/fdroid/repo/com.performancetweaker.app_0.1.11.apk
wget https://apt.izzysoft.de/fdroid/repo/sk.henrichg.phoneprofilesplus_3.5.5.9.apk
wget https://apt.izzysoft.de/fdroid/repo/com.angelgladin.photoexiftoolkit_1.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.afollestad.photoaffix_2017-05-30.apk
wget https://apt.izzysoft.de/fdroid/repo/friimaind.piholedroid_1.0.4.apk
wget https://apt.izzysoft.de/fdroid/repo/org.esteban.piano_1.6.apk
wget https://apt.izzysoft.de/fdroid/repo/shinado.indi.piping_1.0.01.apk
wget https://apt.izzysoft.de/fdroid/repo/de.pixart.openmessenger_1.19.2.apk
wget https://apt.izzysoft.de/fdroid/repo/screen.dimmer.pixelfilter_2017-02-19.apk
wget https://apt.izzysoft.de/fdroid/repo/de.arcus.playmusicexporter2_2017-05-06.apk
wget https://apt.izzysoft.de/fdroid/repo/org.marco45.polarheartmonitor_1.6.apk
wget https://apt.izzysoft.de/fdroid/repo/mn.today_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/me.maxdev.popularmoviesapp_2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.aaronjwood.portauthority.free_2.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/eu.power_switch_1.6.1.apk
wget https://apt.izzysoft.de/fdroid/repo/de.florian.processlimit_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.tpb.projects_1.3.2.apk
wget https://apt.izzysoft.de/fdroid/repo/me.sabareesh.trippie_1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/tk.elevenk.proxysetter_0.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.stevenschoen.putionew_4.2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/de.qabel.qabel_0.14.0.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.lgallardo.qbittorrentclient_4.5.5.apk
wget https://apt.izzysoft.de/fdroid/repo/org.qpython.qpy_2.0.9.apk
wget https://apt.izzysoft.de/fdroid/repo/yuku.alkitab.kjv_4.4.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.davidmadethis.quicksend_1.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.quran.labs.androidquran_2.8.01.apk
wget https://apt.izzysoft.de/fdroid/repo/com.iktwo.qutelauncher_0.06.apk
wget https://apt.izzysoft.de/fdroid/repo/com.nikhilparanjape.radiocontrol_4.0.apk
wget https://apt.izzysoft.de/fdroid/repo/de.mkrtchyan.recoverytools_2.4.3.apk
wget https://apt.izzysoft.de/fdroid/repo/de.eidottermihi.raspicheck_1.8.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.fkeglevich.rawdumper_2.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/ahmaabdo.readify.rss_1.4.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.marlonjones.simplereminder_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.example.kyle.reminder_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/me.varunon9.remotecontrolpc_1.4.0.apk
wget https://apt.izzysoft.de/fdroid/repo/wseemann.media.romote_1.0.8.apk
wget https://apt.izzysoft.de/fdroid/repo/eu.thedarken.rootvalidator_2.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/ca.frozen.rpicameraviewer_1.3.apk
wget https://apt.izzysoft.de/fdroid/repo/com.ruesga.rview_2.1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/at.jclehner.rxdroid_0.9.31.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.cryart.sabbathschool_3.2.27.apk
wget https://apt.izzysoft.de/fdroid/repo/com.proxy.sh.safejumper_1.7.apk
wget https://apt.izzysoft.de/fdroid/repo/com.scottyab.safetynet.sample_0.3.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.albalitz.save_1.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.lscore.androidl.scorekeeperapp_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.sagar.screenshift2_1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.googlecode.android_scripting_6.2.0.apk
wget https://apt.izzysoft.de/fdroid/repo/pt.samp.scrumCards_2.3.apk
wget https://apt.izzysoft.de/fdroid/repo/ca.rmen.android.scrumchatter_1.6.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.sefaria.sefaria_3.44.apk
wget https://apt.izzysoft.de/fdroid/repo/com.mrbimc.selinux_11.apk
wget https://apt.izzysoft.de/fdroid/repo/com.battlelancer.seriesguide_39.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.shadowsocks_4.2.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.njlabs.showjava_2.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/another.music.player_1.6.73.apk
wget https://apt.izzysoft.de/fdroid/repo/rusapps.sibcoin.wallet_4.40.12d.apk
wget https://apt.izzysoft.de/fdroid/repo/net.alaindonesia.silectric_1.2.01.apk
wget https://apt.izzysoft.de/fdroid/repo/com.emmanuelmess.simpleaccounting_1.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.shadowsocks.plugin.obfs_local_0.0.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.automattic.simplenote_1.5.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.viper.simplert_1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.nielsmasdorp.sleeply_0.3.1.apk
wget https://apt.izzysoft.de/fdroid/repo/SmartHomeMobile-1.1.2-debug.apk
wget https://apt.izzysoft.de/fdroid/repo/com.pcmehanik.smarttoolkit_2.1.3.apk
wget https://apt.izzysoft.de/fdroid/repo/de.ub0r.android.smsdroid_1.7.2.apk
wget https://apt.izzysoft.de/fdroid/repo/org.addhen.smssync_3.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/SpeedTrig_1.4.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jakehilborn.speedr.prod_1.1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.cameron.spotifyadblocker_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.spynet.camtest_2017-05-13.apk
wget https://apt.izzysoft.de/fdroid/repo/com.arachnoid.sshelper_2017-10-27.apk
wget https://apt.izzysoft.de/fdroid/repo/org.standardnotes.notes_1.4.3.apk
wget https://apt.izzysoft.de/fdroid/repo/org.qtproject.example_1.0-alpha.apk
wget https://apt.izzysoft.de/fdroid/repo/com.james.status_3.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.sthagios.stopmotion_1.0.6.apk
wget https://apt.izzysoft.de/fdroid/repo/de.westnordost.streetcomplete_2.4.apk
wget https://apt.izzysoft.de/fdroid/repo/com.kaiserapps.benkaiser.strettoandroidsync_1.2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/jp.juggler.subwaytooter_1.7.2.apk
wget https://apt.izzysoft.de/fdroid/repo/org.secuso.privacyfriendlysudoku_2.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/edu.cmu.hcii.sugilite_2017-04-19.apk
wget https://apt.izzysoft.de/fdroid/repo/de.spiritcroc.syncsettings_2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/org.secuso.privacyfriendlytapemeasure_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/es.dmoral.tappic_1.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jakewharton.telecine_1.6.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.jaspersoft.android.jaspermobile_2.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/Timberdoodle.apk
wget https://apt.izzysoft.de/fdroid/repo/tr.xip.timetable_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.sorz.lab.tinykeepass_0.3.2.apk
wget https://apt.izzysoft.de/fdroid/repo/es.dmoral.tinylist_2017-01-14.apk
wget https://apt.izzysoft.de/fdroid/repo/io.github.hidroh.tldroid_10.apk
wget https://apt.izzysoft.de/fdroid/repo/com.makingiants.todayhistory_0.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.rakuishi.todo_1.0.2.apk
wget https://apt.izzysoft.de/fdroid/repo/xyz.gsora.toot_0.1.a3c475b.apk
wget https://apt.izzysoft.de/fdroid/repo/touchless-map-1.0.2.apk
wget https://apt.izzysoft.de/fdroid/repo/info.zamojski.soft.towercollector_1.14.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.traccar.manager_2.4.apk
wget https://apt.izzysoft.de/fdroid/repo/org.zephyrsoft.trackworktime_1.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/org.transdroid.full_2.5.8.apk
wget https://apt.izzysoft.de/fdroid/repo/me.kartikarora.transfersh_1.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.mercycorps.translationcards_1.1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.wycliffeassociates.translationrecorder_0.8.5.apk
wget https://apt.izzysoft.de/fdroid/repo/com.albertoabruzzo.ymp3d_1.0.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.smedic.tubtub_2.1.apk
wget https://apt.izzysoft.de/fdroid/repo/de.tum.in.tumcampus_1.5.1.apk
wget https://apt.izzysoft.de/fdroid/repo/org.tvbrowser.tvbrowser_0.6.4.apk
wget https://apt.izzysoft.de/fdroid/repo/Tweetin.5.0.0.apk
wget https://apt.izzysoft.de/fdroid/repo/de.vanita5.twittnuker_2.0.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.sjj.echo.umsinterface_1.3.5.apk
wget https://apt.izzysoft.de/fdroid/repo/org.emunix.unipatcher_0.14.2.apk
wget https://apt.izzysoft.de/fdroid/repo/remote.hid.keyboard.client_1.16.apk
wget https://apt.izzysoft.de/fdroid/repo/com.khmelenko.lab.varis_1.00.011.apk
wget https://apt.izzysoft.de/fdroid/repo/altcoin.br.vcash_2017-02-21.apk
wget https://apt.izzysoft.de/fdroid/repo/com.pluscubed.velociraptor_1.5.6.apk
wget https://apt.izzysoft.de/fdroid/repo/com.github.xfalcon.vhosts_1.6.4.apk
wget https://apt.izzysoft.de/fdroid/repo/de.visorapp.visor_1.5.0.apk
wget https://apt.izzysoft.de/fdroid/repo/org.volkszaehler.volkszaehlerapp_0.9.5.apk
wget https://apt.izzysoft.de/fdroid/repo/net.hyx.app.volumenotification_0.9.5.apk
wget https://apt.izzysoft.de/fdroid/repo/androidVTS_13.apk
wget https://apt.izzysoft.de/fdroid/repo/com.dobi.walkingsynth_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.ronakmanglani.watchlist_1.2.apk
wget https://apt.izzysoft.de/fdroid/repo/ai.agusibrahim.xhrlog_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.quinn.githubknife_2016-10-24.apk
wget https://apt.izzysoft.de/fdroid/repo/org.kochka.android.weightlogger_2.1.1.apk
wget https://apt.izzysoft.de/fdroid/repo/com.QuarkLabs.BTCeClient_2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/what.whatandroid_2.1.7..apk
wget https://apt.izzysoft.de/fdroid/repo/menion.android.whereyougo_0.9.2.apk
wget https://apt.izzysoft.de/fdroid/repo/whispeer.app_0.2.12.apk
wget https://apt.izzysoft.de/fdroid/repo/org.laurentsebag.wifitimer_1.3.0.apk
wget https://apt.izzysoft.de/fdroid/repo/com.example.android.wifidirect_1.0.apk
wget https://apt.izzysoft.de/fdroid/repo/WifiLocationLogger-debug.apk
wget https://apt.izzysoft.de/fdroid/repo/de.hannesstruss.windfish_1.2.2.apk
wget https://apt.izzysoft.de/fdroid/repo/uk.org.platitudes.wipefiles-v0.3-2016022214.apk
wget https://apt.izzysoft.de/fdroid/repo/com.xda.labs_1.1.3.3b.apk
wget https://apt.izzysoft.de/fdroid/repo/com.stripe1.xmouse_2017-01-06.apk
wget https://apt.izzysoft.de/fdroid/repo/com.phantom.onetapvideodownload_3.7.apk
wget https://apt.izzysoft.de/fdroid/repo/xSocks-v1.5.0.apk
wget https://apt.izzysoft.de/fdroid/repo/at.huber.youtubeDownloader_1.6.0.apk
wget https://apt.izzysoft.de/fdroid/repo/jp.hazuki.yuzubrowser_3.3.3.apk
wget https://apt.izzysoft.de/fdroid/repo/im.zom.messenger_15.3.12.apk
wget https://apt.izzysoft.de/fdroid/repo/com.zulip.android_1.3.2.apk
wget https://apt.izzysoft.de/fdroid/repo/com.google.zxing.client.android_4.7.7.apk
wget https://apt.izzysoft.de/fdroid/repo/com.BibleQuote_1.1.84.apk